# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_connectivity_cpp <- function(connectivity, sampling_indices, cluster_assignments) {
    .Call('_ClustAssess_update_connectivity_cpp', PACKAGE = 'ClustAssess', connectivity, sampling_indices, cluster_assignments)
}

